# Generated by Django 4.1.6 on 2023-07-25 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_give', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='status',
            field=models.CharField(default='Success', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='time',
            name='days',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Deposit Balance'),
        ),
    ]
