# Generated by Django 4.1.6 on 2023-07-25 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_give', '0002_time_status_alter_time_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='status',
        ),
        migrations.AlterField(
            model_name='time',
            name='days',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Days'),
        ),
    ]
