# Generated by Django 4.1.6 on 2023-07-25 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_give', '0004_transactions_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Days')),
            ],
        ),
        migrations.DeleteModel(
            name='Time',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='currency',
            new_name='Currency',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='deposit',
            new_name='Deposit',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='received',
            new_name='Received',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='status',
            new_name='Status',
        ),
    ]
