# Generated by Django 4.1.6 on 2023-07-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_give', '0005_slot_delete_time_rename_address_transactions_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='Status',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Wallet Address'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Currency',
            field=models.CharField(blank=True, max_length=50, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Deposit',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Received',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, verbose_name='Received'),
        ),
    ]
