# Generated by Django 4.1.6 on 2023-07-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_give', '0006_remove_transactions_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Deposit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Received',
            field=models.CharField(blank=True, max_length=50, verbose_name='Received'),
        ),
    ]
