# Generated by Django 4.1.6 on 2023-07-27 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_give', '0008_alter_slot_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slots',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Slots Left'),
        ),
    ]
